# --- Tool completions ---
# Generated by setup/comp.sh (guards on `command -v`, unlike a naive redirect
# which would create an empty completion file for a tool that isn't installed).
fpath+=${XDG_DATA_HOME}/zsh/completions
[[ "$(uname)" == "Darwin" ]] && fpath+=${HOMEBREW_PREFIX}/share/zsh/site-functions

# --- Load complist before compinit (required for menuselect) ---
zmodload zsh/complist

autoload -Uz compinit
compinit

# --- Completion behavior ---
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle ':completion:*' menu select
zstyle ':completion:*:default' list-colors "${LS_COLORS}"

setopt AUTO_PARAM_SLASH
LISTMAX=0
unsetopt pathdirs

# --- Menuselect keybindings ---
bindkey -M menuselect '^I'    menu-complete          # Tab: next candidate
bindkey -M menuselect '^[[Z'  reverse-menu-complete  # Shift-Tab: prev candidate
bindkey -M menuselect '^M'    accept-line            # Enter: accept
bindkey -M menuselect '^[[D'  send-break             # Left: exit menu
bindkey -M menuselect '^[[C'  send-break             # Right: exit menu

# --- fzf: Ctrl-T (insert file path), Alt-C (cd into directory) ---
if command -v fzf >/dev/null 2>&1; then
  if fzf --help 2>&1 | grep -q -- '--zsh'; then
    source <(fzf --zsh)
  else
    for fzf_zsh_file in \
      /usr/share/fzf/completion.zsh \
      /usr/share/fzf/key-bindings.zsh \
      /usr/share/doc/fzf/examples/completion.zsh \
      /usr/share/doc/fzf/examples/key-bindings.zsh \
      "${HOMEBREW_PREFIX:-}/opt/fzf/shell/completion.zsh" \
      "${HOMEBREW_PREFIX:-}/opt/fzf/shell/key-bindings.zsh"; do
      [[ -r "$fzf_zsh_file" ]] && source "$fzf_zsh_file"
    done
    unset fzf_zsh_file
  fi
fi
