# --- Tool completions ---
# Generated by setup/comp.sh (guards on `command -v`, unlike a naive redirect
# which would create an empty completion file for a tool that isn't installed).
fpath+=${XDG_DATA_HOME}/zsh/completions
[[ "$(uname)" == "Darwin" ]] && fpath+=${HOMEBREW_PREFIX}/share/zsh/site-functions

# --- Load complist before compinit (required for menuselect) ---
zmodload zsh/complist

autoload -Uz compinit
compinit

# --- Completion behavior ---
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/.zcompcache"
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle ':completion:*' menu select
zstyle ':completion:*:default' list-colors "${LS_COLORS}"

setopt AUTO_PARAM_SLASH
LISTMAX=0
unsetopt pathdirs

# --- Menuselect keybindings ---
bindkey -M menuselect '^I'    menu-complete          # Tab: next candidate
bindkey -M menuselect '^[[Z'  reverse-menu-complete  # Shift-Tab: prev candidate
bindkey -M menuselect '^M'    accept-line            # Enter: accept
bindkey -M menuselect '^[[D'  send-break             # Left: exit menu
bindkey -M menuselect '^[[C'  send-break             # Right: exit menu
